name: Publish to PyPI (Simple)

on:
  workflow_dispatch:
    inputs:
      test_pypi:
        description: 'Publish to Test PyPI instead of PyPI'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev

    - name: Install maturin
      run: pip install maturin

    - name: Build and publish to Test PyPI
      if: ${{ github.event.inputs.test_pypi == 'true' }}
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        maturin publish --repository testpypi --username __token__ --password "$MATURIN_PYPI_TOKEN"

    - name: Build and publish to PyPI
      if: ${{ github.event.inputs.test_pypi != 'true' }}
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        maturin publish --username __token__ --password "$MATURIN_PYPI_TOKEN"